/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		'./app/**/*.{js,jsx,ts,tsx}',
		'./components/**/*.{js,jsx,ts,tsx}',
		'./src/**/*.{js,jsx,ts,tsx}',
	],
	presets: [require('nativewind/preset')],
	theme: {
		extend: {
			colors: {
				primary: '#AB77F1',
				'primary-dark': '#7C3AED',
				secondary: '#302D33',
				gray100: '#F8F6F2',
				gray200: '#F2EFE9',
				gray300: '#E7E5E4',
				gray400: '#C7C3BD',
				gray500: '#A8A29E',
				gray600: '#78716C',
				gray700: '#57534E',
				gray800: '#292524',
				gray900: '#1C1917',
				white: '#FFFFFF',
				'bg-light': '#F8F6F2',
				'bg-dark': '#171412',
				'bg-tonal': '#F2EFE9',
				'on-dark': '#E8E8E8',
				'image-placeholder': '#E5E1D8',
				divider: '#E7E5E4',
				'divider-dark': '#292524',
				accent: '#00E9C8',
				error: '#EF4444',
				'error-alt': '#F43F5E',
				success: '#00BC7D',
			},
			fontFamily: {
				sans: ['Pretendard-Regular'],
				'pretendard-regular': ['Pretendard-Regular'],
				'pretendard-light': ['Pretendard-Light'],
				'pretendard-medium': ['Pretendard-Medium'],
				'pretendard-semibold': ['Pretendard-SemiBold'],
				'pretendard-bold': ['Pretendard-Bold'],
				hahmlet: ['Hahmlet_400Regular'],
				'hahmlet-semibold': ['Hahmlet_600SemiBold'],
				'hahmlet-bold': ['Hahmlet_700Bold'],
			},
		},
	},
	plugins: [],
};
