-- SPEC-EXHIBITIONS-API-001
-- Creates public.exhibitions table with public-read RLS, then seeds it with the
-- 6 exhibitions currently hardcoded in src/data/exhibitions.ts.
-- posterImage / imageSource (local require() assets) are intentionally excluded.

create table public.exhibitions (
  id                      text primary key,
  title                   text not null,
  venue                   text not null,
  venue_address           text,
  start_date              text not null,
  end_date                text not null,
  artist                  text,
  curator                 text,
  curator_note            text,
  description             text not null,
  poster_color            text not null,
  open_hours              text not null,
  closed_days             text,
  admission               text not null,
  admission_free          boolean not null default false,
  ticket_url              text,
  latitude                double precision,
  longitude               double precision,
  artworks                jsonb not null default '[]'::jsonb,
  related_exhibition_ids  text[] not null default '{}',
  tags                    text[],
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

alter table public.exhibitions enable row level security;

create policy "exhibitions_public_read"
  on public.exhibitions
  for select
  to anon, authenticated
  using (true);

insert into public.exhibitions (
  id, title, venue, venue_address, start_date, end_date, artist, curator, curator_note,
  description, poster_color, open_hours, closed_days, admission, admission_free, ticket_url,
  latitude, longitude, artworks, related_exhibition_ids, tags
) values
(
  $str$1$str$,
  $str$모네, 빛을 그리다$str$,
  $str$예술의전당$str$,
  null,
  $str$2026.05.01$str$,
  $str$2026.08.31$str$,
  $str$클로드 모네$str$,
  null,
  $str$모네는 단순히 사물을 그리지 않았습니다. 그는 빛이 사물 위에서 어떻게 춤추는지를 포착했습니다. 이번 전시는 그 빛의 여정을 따라가며, 관람객이 직접 인상주의의 탄생 순간을 체험할 수 있도록 구성했습니다.$str$,
  $str$인상주의의 대가 클로드 모네의 대표작 60여 점을 한자리에서 만날 수 있는 특별전입니다. 빛과 색채의 마법사 모네가 포착한 순간들, 수련 연작부터 루앙 대성당까지 그의 예술 세계를 깊이 있게 탐구합니다.$str$,
  $str$#E8D5B7$str$,
  $str$10:00 – 20:00$str$,
  $str$매주 월요일$str$,
  $str$성인 18,000원$str$,
  false,
  $str$https://tickets.interpark.com$str$,
  37.4784,
  127.0082,
  $json$[{"id":"a1-1","title":"수련","artist":"클로드 모네","year":"1906","thumbnailColor":"#7BA7A7","frameRatio":"1:1","medium":"캔버스에 유화","dimensions":"89.5 × 92.7 cm","description":"모네가 지베르니의 정원 연못을 바라보며 완성한 연작 중 하나입니다. 물 위에 반영된 하늘과 수련의 경계가 허물어지며, 빛과 색채만이 남는 인상주의의 정수를 보여줍니다.","collection":"시카고 미술관","collectionCity":"시카고, 미국"},{"id":"a1-2","title":"루앙 대성당","artist":"클로드 모네","year":"1894","thumbnailColor":"#C4A882","frameRatio":"2:3","medium":"캔버스에 유화","dimensions":"100 × 65 cm","description":"모네는 루앙 대성당의 정면을 서로 다른 시간대와 날씨 조건에서 30여 점 연작으로 담았습니다. 빛의 변화에 따라 달라지는 석조 건물의 표면이 마치 살아 숨쉬는 듯합니다.","collection":"오르세 미술관","collectionCity":"파리, 프랑스"},{"id":"a1-3","title":"인상, 해돋이","artist":"클로드 모네","year":"1872","thumbnailColor":"#6B8BA4","frameRatio":"4:3","medium":"캔버스에 유화","dimensions":"48 × 63 cm","description":"르아브르 항구의 새벽을 담은 이 작품은 \"인상주의\"라는 미술 운동의 이름 자체가 된 그림입니다. 안개 속 흐릿한 윤곽과 주황빛 태양의 대비가 강렬한 인상을 남깁니다.","collection":"마르모탕 모네 미술관","collectionCity":"파리, 프랑스"},{"id":"a1-4","title":"건초더미","artist":"클로드 모네","year":"1891","thumbnailColor":"#D4A55A"},{"id":"a1-5","title":"포플러","artist":"클로드 모네","year":"1891","thumbnailColor":"#8CAF6E"}]$json$::jsonb,
  ARRAY[$str$4$str$, $str$6$str$]::text[],
  ARRAY[$str$인상주의$str$, $str$풍경화$str$, $str$빛과 색채$str$, $str$명화$str$]::text[]
),
(
  $str$2$str$,
  $str$이중섭 특별전$str$,
  $str$국립현대미술관$str$,
  null,
  $str$2026.04.10$str$,
  $str$2026.07.20$str$,
  $str$이중섭$str$,
  null,
  $str$이중섭의 예술은 고통 속에서도 꺼지지 않는 인간의 의지를 담고 있습니다. 그의 붓질 하나하나에는 가족을 향한 그리움과 조국에 대한 사랑이 배어 있습니다.$str$,
  $str$한국 근현대 미술의 거장 이중섭의 탄생 110주년을 기념하는 대규모 회고전입니다.$str$,
  $str$#D5E8D4$str$,
  $str$10:00 – 18:00$str$,
  $str$매주 월요일$str$,
  $str$무료$str$,
  true,
  $str$https://www.mmca.go.kr$str$,
  37.5789,
  126.98,
  $json$[{"id":"a2-1","title":"황소","artist":"이중섭","year":"1953","thumbnailColor":"#8B6914","frameRatio":"4:3","medium":"종이에 유화","dimensions":"35.5 × 52 cm","description":"한국 근현대 미술의 가장 상징적인 작품 중 하나입니다. 억압과 저항을 상징하는 황소의 눈빛과 근육질의 몸체에서 격동의 한국 근현대사와 작가의 고뇌가 동시에 느껴집니다.","collection":"국립현대미술관","collectionCity":"서울, 한국"},{"id":"a2-2","title":"흰 소","artist":"이중섭","year":"1954","thumbnailColor":"#E8E0D0"},{"id":"a2-3","title":"길 떠나는 가족","artist":"이중섭","year":"1954","thumbnailColor":"#A0866C"},{"id":"a2-4","title":"두 아이","artist":"이중섭","year":"1955","thumbnailColor":"#C8B89A"}]$json$::jsonb,
  ARRAY[$str$4$str$, $str$1$str$]::text[],
  ARRAY[$str$근현대미술$str$, $str$한국화$str$, $str$회고전$str$, $str$거장$str$]::text[]
),
(
  $str$3$str$,
  $str$달리 초현실주의$str$,
  $str$세종문화회관$str$,
  null,
  $str$2026.06.01$str$,
  $str$2026.09.15$str$,
  $str$살바도르 달리$str$,
  null,
  $str$달리의 세계에는 논리가 없습니다. 오직 꿈과 무의식만이 있을 뿐입니다. 이번 전시는 그 기묘하고 매혹적인 세계로 당신을 초대합니다.$str$,
  $str$초현실주의 거장 살바도르 달리의 회화, 조각, 드로잉 80여 점을 선보이는 국내 최대 규모의 달리 전시입니다.$str$,
  $str$#D4D5E8$str$,
  $str$10:00 – 19:00$str$,
  null,
  $str$성인 20,000원$str$,
  false,
  $str$https://tickets.interpark.com$str$,
  37.5724,
  126.9769,
  $json$[{"id":"a3-1","title":"기억의 지속","artist":"살바도르 달리","year":"1931","thumbnailColor":"#C4B896","frameRatio":"4:3","medium":"캔버스에 유화","dimensions":"24.1 × 33 cm","description":"녹아내리는 시계와 황량한 해변이 펼쳐지는 이 소품은 달리의 가장 유명한 작품입니다. 시간의 유동성과 무의식의 세계를 탁월하게 표현했으며, 초현실주의의 교과서로 불립니다.","collection":"뉴욕 현대미술관 (MoMA)","collectionCity":"뉴욕, 미국"},{"id":"a3-2","title":"코끼리","artist":"살바도르 달리","year":"1948","thumbnailColor":"#8899AA"},{"id":"a3-3","title":"성 안토니우스의 유혹","artist":"살바도르 달리","year":"1946","thumbnailColor":"#B8956E"},{"id":"a3-4","title":"꿈","artist":"살바도르 달리","year":"1937","thumbnailColor":"#9AADBC"}]$json$::jsonb,
  ARRAY[$str$5$str$, $str$6$str$]::text[],
  ARRAY[$str$초현실주의$str$, $str$현대미술$str$, $str$조각$str$, $str$드로잉$str$]::text[]
),
(
  $str$4$str$,
  $str$김환기 회고전$str$,
  $str$환기미술관$str$,
  null,
  $str$2026.05.01$str$,
  $str$2026.09.30$str$,
  $str$김환기$str$,
  null,
  null,
  $str$한국 추상미술의 선구자 김환기의 탄생 110주년을 기념하는 대규모 회고전.$str$,
  $str$#D4C5B0$str$,
  $str$10:00 – 18:00$str$,
  $str$매주 월요일$str$,
  $str$성인 10,000원$str$,
  false,
  null,
  37.5844,
  126.9676,
  $json$[{"id":"a4-1","title":"어디서 무엇이 되어 다시 만나랴","artist":"김환기","year":"1970","thumbnailColor":"#3A5A8C"},{"id":"a4-2","title":"19-VII-71","artist":"김환기","year":"1971","thumbnailColor":"#4A6A9C"},{"id":"a4-3","title":"산월","artist":"김환기","year":"1960","thumbnailColor":"#6A8A6C"},{"id":"a4-4","title":"론도","artist":"김환기","year":"1938","thumbnailColor":"#8A7A5C"}]$json$::jsonb,
  ARRAY[$str$1$str$, $str$2$str$]::text[],
  ARRAY[$str$추상미술$str$, $str$한국화$str$, $str$회고전$str$, $str$점·선·면$str$]::text[]
),
(
  $str$5$str$,
  $str$KAWS: HOLIDAY$str$,
  $str$롯데뮤지엄$str$,
  null,
  $str$2026.06.15$str$,
  $str$2026.10.01$str$,
  $str$KAWS$str$,
  null,
  null,
  $str$세계적인 팝 아티스트 KAWS의 아시아 순회 전시.$str$,
  $str$#B8CCB8$str$,
  $str$10:00 – 20:00$str$,
  null,
  $str$성인 18,000원$str$,
  false,
  $str$https://tickets.lottemuseum.com$str$,
  37.5133,
  127.1028,
  $json$[{"id":"a5-1","title":"COMPANION","artist":"KAWS","year":"2020","thumbnailColor":"#4A4A4A"},{"id":"a5-2","title":"BFF","artist":"KAWS","year":"2018","thumbnailColor":"#E8A0C8"},{"id":"a5-3","title":"SHARE","artist":"KAWS","year":"2021","thumbnailColor":"#6A8AAC"},{"id":"a5-4","title":"ALONG THE WAY","artist":"KAWS","year":"2019","thumbnailColor":"#8A6A5C"}]$json$::jsonb,
  ARRAY[$str$3$str$, $str$6$str$]::text[],
  ARRAY[$str$팝아트$str$, $str$현대미술$str$, $str$설치$str$, $str$컬래버$str$]::text[]
),
(
  $str$6$str$,
  $str$반 고흐: 별이 빛나는 밤$str$,
  $str$DDP 갤러리$str$,
  null,
  $str$2026.04.01$str$,
  $str$2026.08.15$str$,
  $str$빈센트 반 고흐$str$,
  null,
  $str$고흐의 별이 빛나는 밤은 단순한 그림이 아닙니다. 그것은 절망 속에서도 빛을 찾으려 했던 한 인간의 절규입니다. 몰입형 미디어아트로 재탄생한 이 작품은 관람객을 그 밤하늘 한가운데로 데려갑니다.$str$,
  $str$몰입형 미디어아트로 재탄생한 반 고흐의 세계.$str$,
  $str$#C8C5D8$str$,
  $str$10:00 – 21:00$str$,
  null,
  $str$성인 20,000원$str$,
  false,
  $str$https://tickets.interpark.com$str$,
  37.5673,
  127.0095,
  $json$[{"id":"a6-1","title":"별이 빛나는 밤","artist":"빈센트 반 고흐","year":"1889","thumbnailColor":"#2A4A8A","frameRatio":"4:3","medium":"캔버스에 유화","dimensions":"73.7 × 92.1 cm","description":"생레미드프로방스의 정신병원에서 바라본 밤하늘을 담은 작품입니다. 소용돌이치는 하늘과 빛나는 별들, 조용히 잠든 마을의 대비가 극적인 내면의 감정을 드러냅니다.","collection":"뉴욕 현대미술관 (MoMA)","collectionCity":"뉴욕, 미국"},{"id":"a6-2","title":"해바라기","artist":"빈센트 반 고흐","year":"1888","thumbnailColor":"#D4A824","frameRatio":"3:4","medium":"캔버스에 유화","dimensions":"92.1 × 73 cm","description":"아를에 머물던 시기 고갱을 맞이하기 위해 그린 연작 중 하나입니다. 노란색의 무한한 변주 속에서 삶에 대한 고흐의 열정과 집착이 고스란히 드러납니다.","collection":"내셔널 갤러리","collectionCity":"런던, 영국"},{"id":"a6-3","title":"자화상","artist":"빈센트 반 고흐","year":"1889","thumbnailColor":"#6A9A8C"},{"id":"a6-4","title":"아를의 침실","artist":"빈센트 반 고흐","year":"1888","thumbnailColor":"#7A9AC4"}]$json$::jsonb,
  ARRAY[$str$1$str$, $str$3$str$]::text[],
  ARRAY[$str$후기인상주의$str$, $str$몰입형$str$, $str$미디어아트$str$, $str$야간관람$str$]::text[]
);
