-- Auto-generated exhibition tags (2026-08-17)
BEGIN;
UPDATE exhibitions SET tags = '{"영상·미디어","국제전","레트로·아카이브"}' WHERE id = 2 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"도자기","식물·꽃","문화유산","한국 역사","기증·기념"}' WHERE id = 4 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"바다","문화유산","한국 역사","철학·사유"}' WHERE id = 5 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"도자기","전통·민속"}' WHERE id = 14 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","개념미술"}' WHERE id = 17 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","근·현대"}' WHERE id = 36 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"구상미술"}' WHERE id = 62 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술"}' WHERE id = 64 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"사진","문화유산","한국 역사","소장품전","기증·기념"}' WHERE id = 85 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"자연·생태","문화유산"}' WHERE id = 86 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"빛·조명","기억·아카이브","문화유산","철학·사유","감정·감각"}' WHERE id = 89 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"식물·꽃","문화유산","한국 역사"}' WHERE id = 95 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"자연·생태","한국 역사"}' WHERE id = 99 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치","문화유산","한국 역사","철학·사유","상설전시"}' WHERE id = 118 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"영상·미디어","기억·아카이브","과학·기술","교육·체험","상설전시"}' WHERE id = 147 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치","건축","자연·생태","기억·아카이브","한국 역사"}' WHERE id = 159 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","몸·마음","국제전","상설전시"}' WHERE id = 174 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"판화"}' WHERE id = 5861 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","참여·체험"}' WHERE id = 5862 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"디지털·미디어아트","패션·의상"}' WHERE id = 5863 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"패션·의상"}' WHERE id = 5864 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"자연·생태","감정·감각","음악·사운드"}' WHERE id = 5865 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"섬유·직물"}' WHERE id = 5866 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"한국화"}' WHERE id = 5867 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","철학·사유"}' WHERE id = 5868 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술"}' WHERE id = 5869 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"한국화","감정·감각","소장품전","상설전시"}' WHERE id = 5870 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"드로잉","회화","언어·텍스트","국제전","한국현대미술"}' WHERE id = 5871 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"영상·미디어","회화","국제전"}' WHERE id = 5872 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","소장품전","참여·체험","상설전시"}' WHERE id = 5874 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"소장품전","상설전시"}' WHERE id = 5879 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"한국 역사"}' WHERE id = 5880 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"식물·꽃","철학·사유","감정·감각"}' WHERE id = 5881 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"사진","인물·초상","국제전"}' WHERE id = 5882 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"사진"}' WHERE id = 5883 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"한국화","국제전"}' WHERE id = 5884 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","그래픽 디자인"}' WHERE id = 5886 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화, 조형 예술"}' WHERE id = 5887 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치"}' WHERE id = 5889 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","자연·생태","식물·꽃","전통·민속","동시대미술"}' WHERE id = 5890 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"소장품전","신진작가"}' WHERE id = 5892 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술"}' WHERE id = 5893 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","국제전"}' WHERE id = 5894 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"영상·미디어","동시대미술","감정·감각"}' WHERE id = 5895 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치","철학·사유","감정·감각","교육·체험"}' WHERE id = 5900 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","종교·신화","소장품전","국제전","상설전시"}' WHERE id = 5903 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","자연·생태","철학·사유","소장품전","상설전시"}' WHERE id = 5904 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"동시대미술"}' WHERE id = 5905 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"영상·미디어","기억·아카이브","철학·사유","사회·정치","교육·체험"}' WHERE id = 5906 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"감정·감각","교육·체험","국제전"}' WHERE id = 5910 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","철학·사유"}' WHERE id = 5911 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"꿈·환상","음악·사운드"}' WHERE id = 5913 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치","자연·생태","기억·아카이브"}' WHERE id = 5915 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"동시대미술","철학·사유","교육·체험"}' WHERE id = 5917 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"디지털·미디어아트","교육·체험","신진작가"}' WHERE id = 5918 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"영상·미디어","과학·기술"}' WHERE id = 5919 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"동시대미술","철학·사유","과학·기술"}' WHERE id = 5920 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","디지털·미디어아트","식물·꽃","국제전"}' WHERE id = 5926 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치","감정·감각"}' WHERE id = 5927 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"영상·미디어","동물","철학·사유"}' WHERE id = 5928 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","몸·신체","감정·감각","언어·텍스트","몸·마음"}' WHERE id = 5929 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술"}' WHERE id = 5930 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화"}' WHERE id = 5932 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치","꿈·환상"}' WHERE id = 5933 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"사진","자연·생태","바다","철학·사유","감정·감각"}' WHERE id = 5935 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","소장품전","국제전"}' WHERE id = 5936 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"퍼포먼스","건축","음악·사운드"}' WHERE id = 5937 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"철학·사유","사회·정치","환경·기후","교육·체험"}' WHERE id = 5940 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","자연·생태","인물·초상","추상","근·현대"}' WHERE id = 5942 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","철학·사유","사회·정치","음악·사운드"}' WHERE id = 5943 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화"}' WHERE id = 5944 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치","몸·신체","철학·사유","교육·체험"}' WHERE id = 5951 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화, 추상화"}' WHERE id = 5952 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","인상주의"}' WHERE id = 5953 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","도시·일상"}' WHERE id = 5954 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"공예","디지털·미디어아트","패션·의상","국제전"}' WHERE id = 5955 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치","동시대미술","철학·사유","사회·정치","언어·텍스트"}' WHERE id = 5956 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","종이공예"}' WHERE id = 5958 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","빛·조명","추상"}' WHERE id = 5959 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"국제전"}' WHERE id = 5960 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"문화유산","감정·감각","국제전"}' WHERE id = 5962 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","동시대미술","철학·사유","감정·감각","언어·텍스트"}' WHERE id = 5963 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"한국화","자연·생태","전통·민속","동시대미술","감정·감각"}' WHERE id = 5965 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"퍼포먼스","음악·사운드","과학·기술","소장품전","국제전"}' WHERE id = 5967 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"자연·생태","철학·사유","감정·감각","환경·기후","과학·기술"}' WHERE id = 5968 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"식물·꽃","도시·일상","동시대미술","철학·사유","감정·감각"}' WHERE id = 5969 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치","회화","판화","기억·아카이브","문화유산"}' WHERE id = 5970 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"소장품전","기증·기념","상설전시"}' WHERE id = 5972 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"디지털·미디어아트","자연·생태","감정·감각","꿈·환상","언어·텍스트"}' WHERE id = 5973 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"사진","인물·초상","철학·사유"}' WHERE id = 5974 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","자연·생태","식물·꽃","철학·사유","교육·체험"}' WHERE id = 5975 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","기억·아카이브","철학·사유","한국현대미술"}' WHERE id = 5978 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"사진","섬유·직물","자연·생태","동시대미술","철학·사유"}' WHERE id = 5979 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화"}' WHERE id = 7176 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"기억·아카이브","교육·체험","소장품전","한국현대미술"}' WHERE id = 7194 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"근·현대","상설전시"}' WHERE id = 7223 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"근·현대","상설전시"}' WHERE id = 7225 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","식물·꽃","전통·민속","소장품전"}' WHERE id = 7910 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치"}' WHERE id = 7913 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"감정·감각"}' WHERE id = 7914 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"드로잉","판화","소장품전"}' WHERE id = 7915 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","인물·초상","철학·사유","감정·감각","국제전"}' WHERE id = 7916 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화, 드로잉, 미디어아트 등"}' WHERE id = 7917 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"서예, 시각예술"}' WHERE id = 7918 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"판화"}' WHERE id = 7919 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"조각·설치","자연·생태","국제전"}' WHERE id = 7920 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","철학·사유"}' WHERE id = 7921 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"빛·조명","문화유산","감정·감각"}' WHERE id = 7922 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"디지털·미디어아트"}' WHERE id = 8223 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화"}' WHERE id = 8224 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"동시대미술"}' WHERE id = 8225 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"영상·미디어","드로잉","일러스트"}' WHERE id = 8226 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","영상·미디어","자연·생태","기억·아카이브"}' WHERE id = 8227 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","판화","드로잉","국제전"}' WHERE id = 8228 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"패션"}' WHERE id = 8229 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"판화","드로잉","소장품전"}' WHERE id = 8549 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"감정·감각"}' WHERE id = 8574 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","한국현대미술"}' WHERE id = 8578 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"회화","빛·조명","자연·생태"}' WHERE id = 8586 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","소장품전"}' WHERE id = 8590 AND tags IS NULL;
UPDATE exhibitions SET tags = '{"현대미술","국제전"}' WHERE id = 8602 AND tags IS NULL;
COMMIT;